config/routes.rb
Rails.application.routes.draw do
  #--- フロント
  scope module: :front do
    # ログイン/ログアウト
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :signout, to: 'sessions#destroy'

    # ホーム
    root 'home#show'

    resource :users, only: [:edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id, optional: true
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id, optional: true
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id, optional: true
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id, optional: true

  validates :content, presence: true
end

app/models/own_color.rb
class OwnColor < ApplicationRecord
  belongs_to :user

  validates :color1, presence: true, numericality: { in: 0..6 }
  validates :color2, presence: true, numericality: { in: 0..6 }
  validates :color3, presence: true, numericality: { in: 0..6 }
  validates :color4, presence: true, numericality: { in: 0..6 }
  validates :color5, presence: true, numericality: { in: 0..6 }
  validates :color6, presence: true, numericality: { in: 0..6 }
  validates :color7, presence: true, numericality: { in: 0..6 }
  validates :color8, presence: true, numericality: { in: 0..6 }
  validates :color9, presence: true, numericality: { in: 0..6 }
  validates :color10, presence: true, numericality: { in: 0..6 }
  validates :color11, presence: true, numericality: { in: 0..6 }

  # color1~color11の値を百分率に変換した配列を返す
  def to_percents
    total = 0
    (1..11).each do |count|
      total += send("color#{count}")
    end

    (1..11).map do |count|
      (send("color#{count}") / total.to_f) * 100
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_members
  has_many :users, through: :team_members
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :team_members
  has_many :teams, through: :team_members
  has_many :sent_letters, class_name: 'Letter', foreign_key: :sender_id
  has_many :received_letters, class_name: 'Letter', foreign_key: :receiver_id
  has_one :own_color
  has_many :sent_colors, class_name: 'Color', foreign_key: :sender_id
  has_many :received_colors, class_name: 'Color', foreign_key: :receiver_id

  attr_accessor :remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  # メールアドレスを全て小文字にする
  def downcase_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Front::SessionsHelper
  before_action :logged_in_user
end

app/controllers/front/home_controller.rb
class Front::HomeController < ApplicationController
  def show
  end
end

app/controllers/front/sessions_controller.rb
class Front::SessionsController < ApplicationController
  skip_before_action :logged_in_user, only: %i(new create)

  def new
  end

  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password])
      log_in(@user)
      params[:remember] == '1' ? remember(@user) : forget(@user)

      # 初回ログインかどうかでリダイレクトを切り替え
      if @user.first_flag
        @user.update(first_flag: false)
        redirect_to edit_users_path
      else
        redirect_back_or root_path
      end
    else
      # ログイン失敗
      flash.now[:danger] = 'メールアドレス、又はパスワードが間違っています'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/front/users_controller.rb
class Front::UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_path
    else
      flash.now[:danger] = '入力内容に誤りがあります'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :description, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = 'marble'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/front/home_helper.rb
module Front::HomeHelper
end

app/helpers/front/sessions_helper.rb
module Front::SessionsHelper
  # 渡されたユーザーでログイン
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがアクセスしているユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end
  
  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  # ユーザーのログインを確認する
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
end

app/helpers/front/users_helper.rb
module Front::UsersHelper
end

app/views/front/home/show.html.erb
<h1>Front::Home#show</h1>
<p>Find me in app/views/front/home/index.html.erb</p>

<%= link_to 'ログアウト', signout_path, method: :delete %>

app/views/front/users/edit.html.erb
<% provide(:title, "プロフィール設定") %>

<%= render 'layouts/header_back', back_path: signout_path, method: :delete %>

<div class="profile-box">
  <h2 class="profile-title">
    プロフィール設定
  </h2>
  プロフィールを設定しよう

  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

  <%= form_with model: @user, url: users_path do |f| %>
    <div class="form-group">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar.variant(resize_to_limit: [100, 100]) %>
      <% end %>
      <%= f.file_field :avatar, class: "form-controle-file" %>
    </div>

    <div class="form-group">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "氏名を入力" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "label" %>
      <%= f.email_field :email, class: "form-control", placeholder: "会社用メールアドレスを入力" %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, class: "label" %>
      <%= f.text_field :phone_number, class: "form-control", placeholder: "社用携帯の番号を入力" %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "label" %>
      <%= f.text_area :description, class: "form-control", placeholder: "自己紹介を入力" %>
    </div>

    <%= f.submit "プロフィールを保存する", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_header_back.html.erb
<div class="header">
  <%= link_to "戻る", back_path, method: method %>
</div>

app/views/layouts/_header_before_signin.html.erb
<div class="header header-before-signin">
  <%= link_to path_name, link_path, class: "header-text" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>